### ISSUE TITLE
Progress Bar is focusable

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-ui#101]
<img width="572" alt="screen shot 2017-03-08 at 6 08 09 pm" src="https://cloud.githubusercontent.com/assets/8146159/23729931/4a8fdbe2-042a-11e7-821e-ff18e5cdad26.png">

I'm not sure if this is an issue or not. I just want to get confirmation this is the expected behavior.

To replicate the screenshot above, navigate to the progress bar and click on it.

**Comment by mmalaker** [comment]
Generally, the only reason for an element to have focus is to perform some action: select, deselect, enter text, etc. Since the progress bar doesn’t have any actions associated to it, there should be no reason for it to receive focus. If at some point we tie an action to the progress bar, say to view more details, then it would receive focus.

**Comment by bjankord** [comment]
Fixed in #120
