### ISSUE TITLE
Update recommended enzyme Intl library

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-ui#155]
# Issue Description
In our internationalization docs, we recommend a specific enzyme Intl library. It seems this library is slower at releasing updates than we had anticipated. We've contributed some updates to enhance the project, yet they haven't been released for some time. I'd like to propose we reconsider which library we recommend for handling Intl when testing with enzyme.

@dev-cprice has developed [enzyme-intl](https://www.npmjs.com/package/enzyme-intl) which has features that would be helpful for testing react-intl with enzyme that I'd recommend we switch to in our internationalization docs. We know the maintainer and so there is less concern the dependency isn't updated as needed. Eventually, I think it would be good to create a terra package specifically for Jest to handle all the configs and concerns around Jest testing with terra, but that is beyond the scope of this issue.

**Comment by dev-cprice** [comment]
So, currently, we use something like: [this](https://github.com/cerner/terra-framework/blob/1de3386f4f788ca8399cac82f772f9d251f46d16/packages/terra-notification-dialog/tests/jest/intl-context-setup.js)

```js
import { IntlProvider, intlShape } from 'react-intl';
import messages from '../../translations/en-US.json';

const locale = 'en-US';
const intlProvider = new IntlProvider({ locale, messages }, {});
const { intl } = intlProvider.getChildContext();

const shallowContext = { context: { intl } };
const mountContext = { context: { intl }, childContextTypes: { intl: intlShape } };

const intlContexts = { shallowContext, mountContext };

export default intlContexts;
```

This is present in [enzyme-intl](https://github.com/dev-cprice/enzyme-intl/blob/master/src/index.js#L25-L27), but instead of exporting the contexts, the enhanced methods are [exported instead](https://github.com/dev-cprice/enzyme-intl/blob/master/src/index.js#L31-L41)

This is also copy-pasted all over the place:
In Terra Core:
![image](https://user-images.githubusercontent.com/34115417/53442972-32d03f00-39d0-11e9-9ded-6a3373e486c7.png)

In Terra Framework:
![image](https://user-images.githubusercontent.com/34115417/53442926-0d433580-39d0-11e9-8f35-fc477b1bd559.png)

The above is then consumed, like so:  [example](https://github.com/cerner/terra-framework/blob/1de3386f4f788ca8399cac82f772f9d251f46d16/packages/terra-notification-dialog/tests/jest/NotificationDialog.test.jsx#L8)

```jsx
import React from 'react';
import intlContexts from './intl-context-setup';
import Component from '../Component';

it('should shallow a Component', () => {
  const wrapper = shallow(<Component />, intlContexts.shallowContext);
  expect(wrapper).toMatchSnapshot();
});
```

This usage requires:
* supplying a context as the second argument to `shallow`, `mount`, and `render`
* copy/pasting the same code throughout terra
* using actual translations, [see here](https://github.com/cerner/terra-framework/blob/1de3386f4f788ca8399cac82f772f9d251f46d16/packages/terra-notification-dialog/tests/jest/intl-context-setup.js#L3)

Using something like [enzyme-intl](https://www.npmjs.com/package/enzyme-intl), we just need to:
* import the method you want, e.g. `shallowWithIntl` or `mountWithIntl`
* use the method instead of the "bare" version, e.g.

```diff
- const wrapper = shallow(<Component />, intlContexts.shallowContext);
+ const wrapper = shallowWithIntl(<Component />);
```

The enzyme-intl package uses the methods described in the [yahoo react-intl docs](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#helper-function-1), however they [don't depend on actual translations](https://github.com/dev-cprice/enzyme-intl/blob/master/src/index.js#L23-L27) through the use of a message proxy object that simply returns the `id`. 

For tests containing the following KVP translation https://github.com/cerner/terra-framework/blob/1de3386f4f788ca8399cac82f772f9d251f46d16/packages/terra-notification-dialog/translations/en.json#L2, snapshots will contain something like:

```diff
- <span>Information</span>
+ <span>Terra.notification.dialog.info</span>
```

This is good because if your snapshot contains an `<IntlProvider />` (**usually** not the case in shallow renders), then the messages object will be present. If the messages object depends on actual translations, then mutating the messages object will cause snapshot tests to fail their diffs.

**Comment by bjankord** [comment]
We've talked about this some in our leadership sync and want to bring the enzyme-intl package into the terra ecosystem as a new package named terra-enzyme-intl.
