### ISSUE TITLE
Windows 10/11 support

### ISSUE THREAD

**Issue by elliott-hoffman-cerner** [cerner/terra-ui#425]
# Feature Request

## Description
In the past terra UI did not support Windows as a development environment. I'd like to change that somehow, because I know many people at Cerner and out in the wild use PCs with Windows and might not have the choice to switch to Linux or macOS. On the other hand: I know that myself and my team might not have easy access to (native) Windows.

This FR can be used as a tracking point to discuss how we might go about adding Windows support. There is no commitment or promise to add Windows support at this time, only a desire to serve our consumers better. To do that we must discuss more.

## Additional Context / Screenshots
I tried a simple experiment before logging this ticket - could I successfully `npm run start` on my macOS host and using [one of the Edge development VMs](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)?

**Conclusion**: No

**Reasons**: 
* I can't use the [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) because those free VMs are too old to [support the WSL](https://docs.microsoft.com/en-us/windows/wsl/install).
* I can't go native, because our repo has file path lengths over 256 length. The VM user does not have access to change the registry to opt-in to longer file paths. This approach fails during the git clone phase.

## @ Mentions
@benbcai @jmsv6d @neilpfeiffer we should discuss this more.

**Comment by elliott-hoffman-cerner** [comment]
We have [Docker instructions](https://engineering.cerner.com/terra-ui/dev_tools/terra-ui/docker-development-environment/about) too. We should consider containers as a work-around.

**Comment by revoyrm** [comment]
To note my team's issues with developing with Terra on windows devices (EDM):

The latest one being file path issues in terra-dev-site v7. The windows file paths contain 2 backslashes `\\` instead a forward slash `/`. The fix is simple, replace the 2 backslashes with a forward slash. Currently it is impossible to use straight windows to run terra-dev-site  v7. 

I did try to use wsl for further development of my uplift but ran into a few issues when trying to make code changes and use git through vscode. Git was incredibly slow to update things like file changes, to commit, to push, to pull, etc. And there were erroneous files showing up as changed (not just line endings) such as come wdio snapshots. Both of these things make using wsl less feasable. 

I discussed with @elliott-hoffman-cerner about the docker instructions but he mentioned they were out of date and wont work. I will try them once it's updated.

We have had other windows development issues in the past to the point that we do not update terra often, due to it. 

I will notify my team members of this to have them share what they remember being an issue. 

Thank you for opening this.

**Comment by benbcai** [comment]
Windows teams should use Docker containers if they have problems developing locally.

**Comment by revoyrm** [comment]
@benbcai  I was told the current docker instructions are out of date and do not work by @elliott-hoffman-cerner  

Are there updated instructions on how to do so anywhere?

**Comment by elliott-hoffman-cerner** [comment]
Hello again. So I looked into this with my team, and at this time we're not going to be spending any effort to supporting a Windows 10/11 development environment - including local containers. Sorry if I got your hopes up - I didn't know this at the time I opened this issue. 

Where can we go from here? 
* **Bad news**: <already listed above 😭>
* **(kinda?) Good news**: We are open to any PR from the community that fixes our docker containers to work. Apparently they've been out of use for quite some time. Maybe one day we'll pull them entirely from the project or fix them, but we are choosing to not focus on that goal in our roadmap. We have some other more critical features and fixes we need to address.
